# Generated by Django 4.2.4 on 2023-09-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custMgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], default='female', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
